### ISSUE TITLE
Windows 10 Build CMakeLists Dependencies Issue 

### ISSUE THREAD

**Issue by NathanW42** [yupi2/synergy#1]
I'm running Windows 10
and trying to build master branch

When building windows in any configuration I am having issues with some dependencies.

Here is the snippet of code where the compiler displays the files not being found
https://gist.github.com/NathanW42/3ddd253810534334e8c1d167f4855235

and here is the full log.
https://gist.github.com/NathanW42/9cfd0f9dcbc27f43297fbed595a86979

**Comment by yupi2** [comment]
I could not reproduce this error from a clean slate. Try deleting your `build` folder and then trying the new build process listed in the `README.md` file (I'm in the process of phasing out usage of `hm`). If it still gives errors then delete that entire repo directory and clone this again anew and try to build that.

**Comment by NathanW42** [comment]
No luck with a clean code of code. I also tried compiling it on a vm with only the dependencies on the synergy compiling page installed.

**Comment by yupi2** [comment]
Mind posting a log of a clean build?
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -G"Visual Studio 14 2015 Win64" ../ >conf.log 2<&1
cmake --build . --config Debug >build.log 2<&1
```

Then gist both `conf.log` and `build.log`

**Comment by NathanW42** [comment]
Here is the config log
https://gist.github.com/NathanW42/fa1236131e8a378f4a97e6f6fce9f4f5
and here is the build log
https://gist.github.com/NathanW42/0bec8f6f5014df412c247a1cf7b9b354

**Comment by yupi2** [comment]
Alright now it seems to only be Qt errors. Adding the MSVC2015-x64 bin path into your %Path% environment variable might fix things up. Try a new **clean** build but add Qt bin folder to your %Path% first:
```
set "Path=%Path%;C:\Qt\5.6.2\msvc2015_64\bin"
```
This is assuming that `C:\Qt\5.6.2\msvc2015_64\` exists. It might not if you didn't select MSVC2015 things in the Qt installer. I'll try to find a way to get CMake to autodetect the folder for the long run though.

**Comment by NathanW42** [comment]
I've just installed Qt 5.6.2 MSVC2015, I previously had Qt 5.6.2 mingw.
I've got "C:\Qt\Qt5.6.2\5.6\winrt_x64_msvc2015\bin" in my %Path% environment variable, but am still failing to get a completed build.

Config Log
https://gist.github.com/NathanW42/dc91830701a0a0c3899332b920fdbf5b

Build Log
https://gist.github.com/NathanW42/0a71313b0257a687d9a7764b4df8b229

**Comment by yupi2** [comment]
winrt is something for mobile devices. You need just msvc2015_64

**Comment by NathanW42** [comment]
Ah ok, thats the only version I could find that was called msvc2015.

**Comment by yupi2** [comment]
You can try this [version of 5.7.1](http://download.qt.io/official_releases/qt/5.7/5.7.1/qt-opensource-windows-x86-msvc2015_64-5.7.1.exe)

**Comment by NathanW42** [comment]
Will do, thanks.

**Comment by NathanW42** [comment]
That worked. Thank you for all your help!

**Comment by yupi2** [comment]
No problem.
