### ISSUE TITLE
Synergy Not Run in Kali Light OS

### ISSUE THREAD

**Issue by Anirbansingha1** [yupi2/synergy#10]
Hi I download and install synergy in kali light os, I used dpkg -i "synergy*.deb" it runs perfectly without any error. When I click in synergy logo it's not running. 
Do I need any other software to install for it.

**Comment by yupi2** [comment]
Try `apt install libqt5widgets5`

**Comment by Anirbansingha1** [comment]
I run below command and run perfectly 
"sudo apt install qtcreator qtbase5-dev cmake make g++ xorg-dev libssl-dev libx11-dev libsodium-dev libgl1-mesa-glx libegl1-mesa libcurl4-openssl-dev libavahi-compat-libdnssd-dev qtdeclarative5-dev libqt5svg5-dev libsystemd-dev"
(https://github.com/symless/synergy-core/wiki/Compiling#ubuntu-1604-and-up)

**Comment by yupi2** [comment]
This issue seems to be solved then.

Note: For compiling this fork, here is a simplified list of packages needed (for Debian/Ubuntu and Fedora) https://github.com/yupi2/synergy#linux--posix-compiling
