### ISSUE TITLE
File missing error while build

### ISSUE THREAD

**Issue by dileep-krishnan** [yupi2/synergy#3]
Hi,
I was trying to build your fork of Synergy in Ubuntu 16.04.2 LTS 64-bit in my VM. I am getting an error as a file is missing 
`RCC: Error in '/home/dileep/Downloads/synergy/synergy/src/gui/res/Synergy.qrc': Cannot find file 'lang/gui_ar.qm'`

The gist for conf log:
https://gist.github.com/dileep-krishnan/179b418d504bbde99b066817158a4b33
The gist for build log:
https://gist.github.com/dileep-krishnan/20ba5443c7f8e072c6494883829a5dcb

Is it something me doing wrong or is the file missing?
I did a clean build and it is repeating.
Thanks in advance!!

**Comment by yupi2** [comment]
`sudo apt-get install qttools5-dev-tools` should install the needed program to built those translation files.

**Comment by yupi2** [comment]
cmake will run the program to build the translations for you by the way

**Comment by dileep-krishnan** [comment]
I have already installed both qttools and cmake. The qttools are version 5.5.1-3build1 and cmake is 3.5.1-1ubuntu3 . The error is repeating.

**Comment by yupi2** [comment]
Does the `lrelease` command work in a terminal for you? I can build synergy fresh on my Ubuntu 16.04 VM. [Here's a list](https://gist.github.com/yupi2/d54f3f095aa30692f9510d15e3f18645) of installed packages I have on my VM. I used `apt list --installed > out.txt` to get get it.

**Comment by yupi2** [comment]
Some packages you should ensure you have are `qtbase5-dev` and `qtbase5-dev-tools`

**Comment by yupi2** [comment]
Actually something that may be more helpful is all the packages I've installed that I found in my `~/.bash_history`

`sudo apt-get install build-essential git cmake g++ xorg-dev libcurl4-openssl-dev libavahi-compat-libdnssd-dev libssl-dev libx11-dev git qtbase5-dev qttools5-dev qttools5-dev-tools`

**Comment by dileep-krishnan** [comment]
Thanks a lot for your help! The build went through. 
It seems that we need `qt4-linguist-tools` to be installed. I don't know from where this dependency is coming from, but, once I installed the linguist tools and did a clean build, it went through.
Once again, thanks a lot for your help!

**Comment by yupi2** [comment]
Yeah it seems Ubuntu uses the Qt4 version as default. The Qt5 appears to be `/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease` which cmake will use if I use some of the functions Qt provides to cmake. Dealing with Qt and cmake is really annoying though and it doesn't like to do what I want so I'll get it fixed eventually

**Comment by yupi2** [comment]
I don't think using cmake to produce .qm files from the .ts files is worth doing. We'll just stick with pre-generated .qm files that will be synced with any new translations if they're ever done. The qt4-linguist-tools dep along with any Qt5 dev tools deps shouldn't be needed anymore.
