### ISSUE TITLE
Issues with Windows installers

### ISSUE THREAD

**Issue by yupi2** [yupi2/synergy#4]
Hi if you have any problems feel free to comment.

**Comment by bbhangoo** [comment]
@yupi2 does this version have almost recent code. In my compiled app from this branch I loose the mouse cursor, it seems stuck on the task bar at the bottom of the screen? Mouse clicks and keyboard events go through OK but I cannot move or see the mouse cursor. Testing between Windows 10 x64 on both ends. The pre-compiled release 1.8.6-stable works OK on the same setup. Did we loose some fixes in the branch ?

**Comment by yupi2** [comment]
@bbhangoo I add changes made in the symless/synergy repo to this one too so this is not missing anything. I do not know of anything I have changed to make the cursor not visible. Will you try changing some options to see if they fix it? In `Configure Server...` --> `Advanced server settings` there's `Enable clipboard sharing` and `Enable drag and drop file transfers`. Does disabling those or also disabling SSL encryptiong do anything? Make sure to restart the server and client after making changes.

**Comment by bbhangoo** [comment]
@yupi2 I disabled everything - clipboard sharing, drag drop & SSL, no change, still loose the cursor. I tried another test, used a Mac server, version 1.8.6 with my built client, that worked OK, just like the 1.8.6 Windows release.

At first I thought it might have something to with the fact that I am running the server in a VMWare VM but the release version of the server works OK in the same VM.

**Comment by yupi2** [comment]
@bbhangoo I have a Win10 client in a VirtualBox VM that gets an invisible cursor. It's caused by the VirtualBox using `Mouse Integration` which hides the cursor in the VM and uses the cursor on the host machine it seems. If VMWare has an option like mouse integration you could try disabling it. It's weird that the 1.8.6 release doesn't have this problem. There's another option in `Advanced server settings` called `Use relative mouse moves` which you can toggle to see if anything changes.

**Comment by bbhangoo** [comment]
@yupi2 Toggle of relative mouse moves did not help. 

I tried another experiment to rule out the Virtual machine theory, ran from raw Windows 10 console to Mac console (no VMs), the release version of the server from the Windows box worked fine, the compiled server did not. Seems like the server compile is missing something, the recompiled client works OK.

Turning on DEBUG seems to show that every time the mouse moves on the client it switches back to the server and ignores consequent mouse events. If you see the log file, the leaving macbook and going back to "yoga" (the windows box) were just mouse movements inside the client.

On the client side log I see -
[2017-05-08T13:05:54] INFO: leaving screen
[2017-05-08T13:05:54] DEBUG: hiding cursor

Somehow it thinks we are back on the server, even though the cursor will become momentarily visible on the client side bottom right corner of the screen, if I move the mouse really fast. Somewhere it has a conflict and ignores all the mouse events as being "bogus" so they do not show on either client or server.

[server.log.txt](https://github.com/yupi2/synergy/files/984701/server.log.txt)

**Comment by yupi2** [comment]
@bbhangoo [Symless has a new release (1.9.0-rc3)](https://symless.com/forums/topic/2587-synergy-v190-release-candidate/) if you feel like testing to see if newer official releases have the same problem.

The cursor being stuck might have something to do with DPI scaling on Windows, whatever that means. https://github.com/symless/synergy/issues/5186 could be related if so

**Comment by bbhangoo** [comment]
@yupi2 tried the new release, it does not have the problem.

Your other hint DID work, it does have to do with DPI scaling, since the resolution on my Lenovo laptop is very high I had scaling on, turning it down to no scaling (100%) fixes the problem. Now the mouse moves across nicely. There must be some code in the releases that handles the scaling that we are missing in this branch.

**Comment by yupi2** [comment]
@bbhangoo Try the `activey` branch to see if it's fixed for you.
```
git pull
git checkout activey
```
Delete the `build` folder the and then build it again.

To run properly on high DPI displays synergys.exe needed Win7 compatibility along with the `Disable display scaling on high DPI settings` option enabled on the synergys.exe Compatibility properties for the executable. The installers would automatically set this on binary installed to `C:\Program Files\Synergy\synergys.exe` so it wouldn't work if you're running Synergy from the build directory directly. A manifest file that is added to synergys.exe at compile-time was removed by Symless in some commit that would keep the compatibility settings on the file so I just added the manifest back.

**Comment by bbhangoo** [comment]
@yupi2 It works perfect! Tried both server and client, both ways.
Somehow I am missing msbuild in my install but I could run them from the command prompt. 
Nice job, thanks!

**Comment by yupi2** [comment]
@bbhangoo msbuild can be used when the Visual Studio environment variables are setup. For example using `VS2015 x64 Native Tools Command Prompt` opens a command-prompt window with the environment variables setup. It should be searchable in the start-menu or in one of the start-menu folders (Visual Studio 2015 -> Visual Studio Tools -> Windows Desktop Command Prompts)

**Comment by bbhangoo** [comment]
@yupi2 thanks a lot, got the installer to build and install the app ok.

**Comment by masterchiller96** [comment]
how can I compile this with visual studio 2017? I have the dependencies but I get cmake errors when I try to use it with the visual studio 2017 generator

**Comment by yupi2** [comment]
@chillgamingaz What's your CMake version, Qt version, Wix version, and %Path% variable? Along with the commands you are running and any logs (you can upload them as a [gist here](https://gist.github.com/)). Also you may need to open a VS2017 command prompt. Search your start menu for something like ~~`VS2015 x64 Native Tools Command Prompt`~~ `VS2017 x64 Native Tools Command Prompt`****.

**Comment by masterchiller96** [comment]
whoops, forgot to get the c++ development environment parts of visual studio installed. that might be my problem, if not I will reply back

**Comment by masterchiller96** [comment]
I fixed my issue, I didn't have all the c++ environment ready in visual studio, had a path issue then had to modify the fix project file to show the correct link for a file

**Comment by yupi2** [comment]
Going to close this - anyone open a new issue if there's problems.
