### ISSUE TITLE
Provide *.deb releases

### ISSUE THREAD

**Issue by rpatterson** [yupi2/synergy#7]
### Operating Systems ###

Server: Ubuntu/Debian
Client: Ubuntu/Debian

### Synergy Version ###

Any

### Steps to reproduce bug ###

1. Go to "Releases" in GitHub
2. There are no `*.deb` releases available

### Other info ###

Are there `*.deb` releases already available anywhere?  If not, I'll work on setting up an apt repo for this fork so that those of us running Debian based Linux distros can keep up-to-date easily.

**Comment by yupi2** [comment]
No any that I've setup - would you like to be added to the repo collaborators to add it?
I'll use this chance to ping @dev-id too if they want to be a collaborator since they've setup Travis support on their fork https://github.com/dev-id/synergy

**Comment by yupi2** [comment]
I'll go ahead and add both of you because I'll be busy for a few hours.

**Comment by rpatterson** [comment]
Thanks for adding me!  Do you want me to just push to master or submit PRs from a branch?

**Comment by yupi2** [comment]
PRs would probably be cleaner - but you can merge whatever you think is ready

**Comment by yupi2** [comment]
.deb files are uploaded to https://github.com/yupi2/synergy/releases now. I haven't tested them and I'm not sure if adding the $version_$branch_$commit stuff to the file name causes problems so if there's any just mention it
